### ISSUE TITLE
merge ifspython into gpipy?

### ISSUE THREAD

**Issue by dsavransky** [geminiplanetimager/gpipy#1]
Would that make sense, rather than making it its own repository?

**Comment by mperrin** [comment]
I think in practice it already is - in the sense that gpipy is derived from and improved on from my earlier ifspython repo. I just didn't ever  delete the old one on svn, though. I dont think there is any reason to migrate any of what is in the ifspython directory to github at all.

On Aug 9, 2016, at 2:46 PM, Dmitry Savransky <notifications@github.com<mailto:notifications@github.com>> wrote:

Would that make sense, rather than making it its own repository?

**Comment by dsavransky** [comment]
What about gpidiagram?

**Comment by dsavransky** [comment]
Merged into gpilib instead.
